"""empty message

Revision ID: f491d827e0e8
Revises: 12ade9aab7cb
Create Date: 2021-11-13 16:46:31.874679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f491d827e0e8'
down_revision = '12ade9aab7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts_inst', 'code')
    op.drop_column('posts_inst', 'views')
    op.drop_column('posts_inst', 'likes')
    op.drop_column('posts_inst', 'comments')
    op.drop_column('posts_inst', 'pk')
    op.drop_column('posts_inst', 'link')
    op.drop_column('posts_inst', 'id_post')
    op.add_column('posts_twit', sa.Column('avg_view_count', sa.Integer(), nullable=True))
    op.add_column('posts_twit', sa.Column('avg_retweet_count', sa.Integer(), nullable=True))
    op.add_column('posts_twit', sa.Column('avg_reply_count', sa.Integer(), nullable=True))
    op.add_column('posts_twit', sa.Column('avg_like_count', sa.Integer(), nullable=True))
    op.add_column('posts_twit', sa.Column('avg_quote_count', sa.Integer(), nullable=True))
    op.add_column('posts_twit', sa.Column('media', sa.Integer(), nullable=True))
    op.add_column('posts_twit', sa.Column('avg_er', sa.Integer(), nullable=True))
    op.add_column('posts_twit', sa.Column('growth', sa.Integer(), nullable=True))
    op.add_column('posts_twit', sa.Column('growth_predict', sa.Integer(), nullable=True))
    op.drop_column('posts_twit', 'quote_count')
    op.drop_column('posts_twit', 'reply_count')
    op.drop_column('posts_twit', 'view_count')
    op.drop_column('posts_twit', 'retweet_count')
    op.drop_column('posts_twit', 'like_count')
    op.drop_column('posts_twit', 'author_id')
    op.drop_column('posts_twit', 'tweet_id')
    op.drop_column('posts_twit', 'tweet_link')
    op.add_column('topics_inst', sa.Column('name', sa.String(length=120), nullable=False))
    op.drop_column('topics_inst', 'avg_er')
    op.drop_column('topics_inst', 'username')
    op.drop_column('topics_inst', 'growth_predict')
    op.drop_column('topics_inst', 'avg_views')
    op.drop_column('topics_inst', 'followers')
    op.drop_column('topics_inst', 'growth')
    op.drop_column('topics_inst', 'media')
    op.drop_column('topics_inst', 'avg_likes')
    op.drop_column('topics_inst', 'avg_comments')
    op.drop_column('topics_twit', 'avg_er')
    op.drop_column('topics_twit', 'avg_like_count')
    op.drop_column('topics_twit', 'avg_retweet_count')
    op.drop_column('topics_twit', 'growth_predict')
    op.drop_column('topics_twit', 'avg_view_count')
    op.drop_column('topics_twit', 'avg_reply_count')
    op.drop_column('topics_twit', 'followers')
    op.drop_column('topics_twit', 'avg_quote_count')
    op.drop_column('topics_twit', 'growth')
    op.drop_column('topics_twit', 'media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics_twit', sa.Column('media', sa.INTEGER(), nullable=True))
    op.add_column('topics_twit', sa.Column('growth', sa.INTEGER(), nullable=True))
    op.add_column('topics_twit', sa.Column('avg_quote_count', sa.INTEGER(), nullable=True))
    op.add_column('topics_twit', sa.Column('followers', sa.INTEGER(), nullable=True))
    op.add_column('topics_twit', sa.Column('avg_reply_count', sa.INTEGER(), nullable=True))
    op.add_column('topics_twit', sa.Column('avg_view_count', sa.INTEGER(), nullable=True))
    op.add_column('topics_twit', sa.Column('growth_predict', sa.INTEGER(), nullable=True))
    op.add_column('topics_twit', sa.Column('avg_retweet_count', sa.INTEGER(), nullable=True))
    op.add_column('topics_twit', sa.Column('avg_like_count', sa.INTEGER(), nullable=True))
    op.add_column('topics_twit', sa.Column('avg_er', sa.INTEGER(), nullable=True))
    op.add_column('topics_inst', sa.Column('avg_comments', sa.INTEGER(), nullable=True))
    op.add_column('topics_inst', sa.Column('avg_likes', sa.INTEGER(), nullable=True))
    op.add_column('topics_inst', sa.Column('media', sa.INTEGER(), nullable=True))
    op.add_column('topics_inst', sa.Column('growth', sa.INTEGER(), nullable=True))
    op.add_column('topics_inst', sa.Column('followers', sa.INTEGER(), nullable=True))
    op.add_column('topics_inst', sa.Column('avg_views', sa.INTEGER(), nullable=True))
    op.add_column('topics_inst', sa.Column('growth_predict', sa.INTEGER(), nullable=True))
    op.add_column('topics_inst', sa.Column('username', sa.VARCHAR(length=120), nullable=False))
    op.add_column('topics_inst', sa.Column('avg_er', sa.INTEGER(), nullable=True))
    op.drop_column('topics_inst', 'name')
    op.add_column('posts_twit', sa.Column('tweet_link', sa.VARCHAR(length=120), nullable=True))
    op.add_column('posts_twit', sa.Column('tweet_id', sa.VARCHAR(length=120), nullable=True))
    op.add_column('posts_twit', sa.Column('author_id', sa.VARCHAR(length=120), nullable=True))
    op.add_column('posts_twit', sa.Column('like_count', sa.INTEGER(), nullable=True))
    op.add_column('posts_twit', sa.Column('retweet_count', sa.INTEGER(), nullable=True))
    op.add_column('posts_twit', sa.Column('view_count', sa.INTEGER(), nullable=True))
    op.add_column('posts_twit', sa.Column('reply_count', sa.INTEGER(), nullable=True))
    op.add_column('posts_twit', sa.Column('quote_count', sa.INTEGER(), nullable=True))
    op.drop_column('posts_twit', 'growth_predict')
    op.drop_column('posts_twit', 'growth')
    op.drop_column('posts_twit', 'avg_er')
    op.drop_column('posts_twit', 'media')
    op.drop_column('posts_twit', 'avg_quote_count')
    op.drop_column('posts_twit', 'avg_like_count')
    op.drop_column('posts_twit', 'avg_reply_count')
    op.drop_column('posts_twit', 'avg_retweet_count')
    op.drop_column('posts_twit', 'avg_view_count')
    op.add_column('posts_inst', sa.Column('id_post', sa.VARCHAR(length=120), nullable=True))
    op.add_column('posts_inst', sa.Column('link', sa.VARCHAR(length=120), nullable=True))
    op.add_column('posts_inst', sa.Column('pk', sa.VARCHAR(length=120), nullable=True))
    op.add_column('posts_inst', sa.Column('comments', sa.INTEGER(), nullable=True))
    op.add_column('posts_inst', sa.Column('likes', sa.INTEGER(), nullable=True))
    op.add_column('posts_inst', sa.Column('views', sa.INTEGER(), nullable=True))
    op.add_column('posts_inst', sa.Column('code', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
